# описание всех компонентов и автоматизация запуска

services:
  app:
    # сборка фласк контейнера из локального докерфайла
    build: .
    # переменные окружения для подключения
    environment: 
      DATABASE_URL: postgresql+psycopg2://flask:flask@db:5432/flaskdb
      REDIS_URL: redis://redis:6379/0
      TASKS_CACHE_TTL: 60
    # старт после базы
    depends_on:
      - db
      - redis
  
  db:
    # минимальный официальный постгрес образ
    image: postgres:16-alpine
    # инициализация учетки и базы
    environment:
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: flask
      POSTGRES_DB: flaskdb
    # сохранение данных 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    # для кеша апи ответов
    image: redis:7-alpine

  nginx:
    # проксирует запрос к flask
    image: nginx:1.27-alpine
    # внешний порт
    ports:
      - "80:80"
    # монтируем конфиг и папку кеша
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_cache:/var/cache/nginx
    # перед стартом ожидание приложения
    depends_on:
      - app

# ну и неймы томов 
volumes:
  postgres_data:
  nginx_cache:

